branches:
  - main
  - master
  - name: "*.x"
    prerelease: true
  - name: "*.x-jsonlogs"
    prerelease: true
ci: true
debug: false
dryRun: false
tagFormat: 'v.${version}'

preset: 'conventionalcommits'




verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  # - '@semantic-release/gitlab'
  # - 'semantic-release-slack-bot'

analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    releaseRules:
      - breaking: true
        release: major
      - type: build
        release: patch
      - type: chore
        release: false
      - type: ci
        release: false
      - type: docs
        release: patch
      - type: feat
        release: patch
        #release: minor
      - type: fix
        release: patch
      - type: perf
        release: patch
      - type: refactor
        release: false
      - type: revert
        release: patch
      - type: style
        release: false
      - type: test
        release: false

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    linkCompare: true
    linkReferences: true
    parserOpts:

      mergePattern: "^Merge branch '(.*)' into (.*)$"
      mergeCorrespondence: ['branch_src', 'branch_dst']
    presetConfig:
      types:
        - type: 'build'
          section: '🛺 CI/CD'
          hidden: false
        - type: 'chore'
          section: 'Other'
          hidden: true
        - type: 'ci'
          section: '🛺 CI/CD'
          hidden: false
        - type: 'docs'
          section: '📔 Docs'
          hidden: false
        - type: 'example'
          section: '📝 Examples'
          hidden: false
        - type: 'feat'
          section: '🚀 Features'
          hidden: false
        - type: 'fix'
          section: '🛠 Fixes'
          hidden: false
        - type: 'perf'
          section: '⏩ Performance'
        - type: 'refactor'
          section: ':scissors: Refactor'
          hidden: false
        - type: 'revert'
          section: '🙅‍♂️ Reverts'
        - type: 'style'
          section: '💈 Style'
        - type: 'test'
          section: '🧪 Tests'
          hidden: false

prepare:
  # - path: '@semantic-release/exec'
  #   verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - path: '@semantic-release/changelog'
  # - path: '@semantic-release/git'
  #   message: 'chore(RELEASE): ${nextRelease.version}'
  #   assets: ['CHANGELOG.md']

publish:
  - path: '@semantic-release/github'

success:
  # - path: 'semantic-release-slack-bot'
  #   notifyOnSuccess: true
  #   markdownReleaseNotes: true
  #   onSuccessTemplate:
  #     channel: 'chanelname'
  #     text: "A new version of $package_name with version `$npm_package_version` has been released"
  #     attachments:
  #       - color: '#00c100'
  #         title: '$package_name'
  #         title_link: '$repo_url'
  #         text: '$release_notes'
  #         footer: 'version: $npm_package_version'


fail: false
  # - path: 'semantic-release-slack-bot'
  #   # publish a message about failure to a slack channel
  #   notifyOnFail: true
